version: "3"
services:
  backend:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: postdb
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    volumes:
      - ./backend:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi-posts
      MYSQL_DATABASE: postdb
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
